
server:
  port: 8080

spring:
  application:
    name: gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1