spring:
  application:
    name: auth

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog-master.yml

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: kamyczkisecretkeyanditissosecureyouwillnotbelive
springdoc:
  api-docs:
    path: /api-docs
