version: '3.8'

include:
- docker-compose-kafka.yml

services:
  registry:
    container_name: eureka_registry
    image: ghcr.io/isaribi/kamyczki:registry
    ports:
      - '8761:8761'
    networks:
      - kamyczki-network

  gateway:
    container_name: gateway
    image: gateway_test:latest
    ports:
      - '8080:8080'
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
      - KAMYCZKI_AUTH-SERVICE=auth:8081
    networks:
      - kamyczki-network
    
  stone-write:
    container_name: stone-write
    image: ghcr.io/isaribi/kamyczki:stone-write
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9200,kafka-broker-2:9210,kafka-broker-3:9220
    depends_on:
      - registry
    ports:
      - '8083:8083'
    networks:
      - kamyczki-network
  
  stone-read:
    container_name: stone-read
    image: ghcr.io/isaribi/kamyczki:stone-read
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9200,kafka-broker-2:9210,kafka-broker-3:9220
    depends_on:
      - db
      - registry
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - '8082:8082'
    networks:
      - kamyczki-network
      
  db:
    container_name: auth_db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - kamyczki-network

  auth:
    container_name: auth
    image: ghcr.io/isaribi/kamyczki:auth
    depends_on:
      - db
      - registry
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    ports:
      - '8081:8081'
    networks:
      - kamyczki-network

networks:
  kamyczki-network:
    driver: bridge

volumes:
  db:
    driver: local