server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

spring:
  application:
    name: stone-read

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog-master.yml
  kafka:
    bootstrap-servers: localhost:9200
    consumer:
      group-id: stone-read-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        enable.auto.commit: false
