spring:
  application:
    name: registry

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true