name: Create and publish Docker images
on:
  push:
    branches:
      - daniel/compose-fix
    paths:
      - 'server/microservices/**'
      - 'server/libraries/**'

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ALL_SERVICES: '["gateway", "auth", "registry", "stone-read", "stone-write"]'

jobs:
  determine-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    
    steps:
      - uses: actions/checkout@v4
      
      - id: set-services
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "server/libraries/\|server/microservices/.*/.*-feign/"; then
            echo "services=$ALL_SERVICES" >> $GITHUB_OUTPUT
          else
            SERVICES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "server/microservices/" | cut -d'/' -f3 | sort -u | jq -R -s -c 'split("\n")[:-1]')
            echo "services=$SERVICES" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: determine-services
    if: fromJson(needs.determine-services.outputs.services)[0] != null
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    strategy:
      matrix:
        platform: ${{ fromJson(needs.determine-services.outputs.services) }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Package for ${{ matrix.platform }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/microservices/${{ matrix.platform }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform }}:latest
          cache-to: type=inline
          provenance: false