name: Create and publish Docker images
on:
  push:
    branches:
      - daniel/compose-fix
    paths:
      - 'server/**'

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      gateway: ${{ steps.filter.outputs.gateway }}
      auth: ${{ steps.filter.outputs.auth }}
      registry: ${{ steps.filter.outputs.registry }}
      stone-read: ${{ steps.filter.outputs.stone-read }}
      stone-write: ${{ steps.filter.outputs.stone-write }}
      shared: ${{ steps.filter.outputs.shared }}
      any_service_changed: ${{ steps.check-changes.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            gateway:
              - 'server/microservices/gateway/**'
            auth:
              - 'server/microservices/auth/auth-service/**'
            registry:
              - 'server/microservices/registry/**'
            stone-read:
              - 'server/microservices/stone-read/**'
            stone-write:
              - 'server/microservices/stone-write/**'
            shared:
              - 'server/libraries/**'
              - 'server/microservices/auth/auth-feign/**'
              - 'server/microservices/**/feign/**'

      - id: check-changes
        run: |
          if [[ "${{ steps.filter.outputs.gateway }}" == "true" || \
                "${{ steps.filter.outputs.auth }}" == "true" || \
                "${{ steps.filter.outputs.registry }}" == "true" || \
                "${{ steps.filter.outputs.stone-read }}" == "true" || \
                "${{ steps.filter.outputs.stone-write }}" == "true" || \
                "${{ steps.filter.outputs.shared }}" == "true" ]]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.any_service_changed == 'true'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - name: gateway
            path: gateway
          - name: auth
            path: auth
          - name: registry
            path: registry
          - name: stone-read
            path: stone-read
          - name: stone-write
            path: stone-write

    if: >-
      needs.detect-changes.outputs.shared == 'true' ||
      needs.detect-changes.outputs[matrix.service.name] == 'true'
    
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service.name }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Package for ${{ matrix.service.name }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/microservices/${{ matrix.service.path }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service.name }}:latest
          cache-to: type=inline
          provenance: false
