name: Create and publish Docker images

on:
  push:
    branches:
      - daniel/compose-fix

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [gateway, auth, registry, stone-read, stone-write]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if service files changed
        id: check_changes
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep "server/microservices/${{ matrix.platform }}" || true)
          echo "changed=${CHANGED:+true}" >> $GITHUB_OUTPUT
          
      - name: Log in to Registry
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.platform }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Package for ${{ matrix.platform }}
            org.opencontainers.image.licenses=MIT
            
      - name: Build and push
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/microservices/${{ matrix.platform }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.platform }}
          cache-to: type=inline