name: Create and publish Docker images

on:
  push:
    branches:
      - daniel/compose-fix

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      shared_changed: ${{ steps.changes.outputs.shared_changed }}
      services_changed: ${{ steps.changes.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create .changes_cache directory
        run: mkdir -p .changes_cache

      - name: Restore changes cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: .changes_cache
          key: changes-${{ github.sha }}
          restore-keys: |
            changes-

      - name: Check changes
        id: changes
        run: |
          if [ -f .changes_cache/shared_changed ]; then
            echo "shared_changed=$(cat .changes_cache/shared_changed)" >> $GITHUB_OUTPUT
            echo "matrix=$(cat .changes_cache/services_changed)" >> $GITHUB_OUTPUT
          else
            SHARED_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E "server/libraries/|server/microservices/.+/.*-feign/" || true)
            echo "shared_changed=${SHARED_CHANGED:+true}" >> $GITHUB_OUTPUT
            SERVICES=$(git diff --name-only HEAD^ HEAD | grep "server/microservices/" | cut -d'/' -f3 | sort -u | jq -R -s -c 'split("\n")[:-1]')
            echo "matrix=$SERVICES" >> $GITHUB_OUTPUT

            mkdir -p .changes_cache
            echo "${SHARED_CHANGED:+true}" > .changes_cache/shared_changed
            echo "$SERVICES" > .changes_cache/services_changed
          fi

      - name: Save changes cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: .changes_cache
          key: changes-${{ github.sha }}

  build-and-push:
    needs: check-changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        platform: ${{ fromJSON(needs.check-changes.outputs.shared_changed == 'true' && '["gateway", "auth", "registry", "stone-read", "stone-write"]' || needs.check-changes.outputs.services_changed) }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Restore Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ matrix.platform }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ matrix.platform }}-

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Package for ${{ matrix.platform }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/microservices/${{ matrix.platform }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          provenance: false