name: Create and publish Docker images

on:
  push:
    branches:
      - DanielWorkflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # Zachowujemy nazwę repozytorium w tej zmiennej
  PLATFORMS: gateway,auth,registry  # Definiuje platformy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [gateway, auth, registry]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.platform }}
        id: push_image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/microservices/${{ matrix.platform }}/Dockerfile
          push: true
          # Użyj bezpiecznego, ręcznego tagowania bez konwersji
          tags: |
            ${{ env.REGISTRY }}/isabiri/kamyczki-${{ matrix.platform }}:latest
          labels: |
            platform=${{ matrix.platform }}

      - name: Generate artifact attestation for ${{ matrix.platform }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/isabiri/kamyczki-${{ matrix.platform }}:latest
          subject-digest: ${{ steps.push_image.outputs.digest }}
          push-to-registry: true
