name: Create and publish Docker images

on:
  push:
    branches:
      - daniel/fix

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: gateway,auth,registry

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [gateway, auth, registry, stone-read, stone-write]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date as tag
        id: date_tag
        run: echo "TAG_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.platform }}
            type=raw,value=${{ env.TAG_DATE }}

      - name: Build and push Docker image for ${{ matrix.platform }}
        id: push_image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/microservices/${{ matrix.platform }}/Dockerfile
          push: true
          tags: |
            ghcr.io/isaribi/kamyczki:${{ matrix.platform }}
            ghcr.io/isaribi/kamyczki:${{ env.TAG_DATE }}  # Użycie tagu z datą
          labels: ${{ steps.meta.outputs.labels }}
