name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v4
        with: 
          java-version: '19'
          distribution: 'temurin'
      - name: Check if the directory exists
        run: ls -la /home/runner/work/Kamyczki/server/registry
      - name: Run the Maven verify phase
        working-directory: /home/runner/work/Kamyczki/server/registry
        run: mvn --batch-mode --update-snapshots verify
