name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: 
          java-version: '19'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: |
          cd ./server/registry
          mvn --batch-mode --update-snapshots verify