name: Java CI
on:
  push:
    branches:
      - daniel/fix
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install commons
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/libraries/commons
      
      - name: Build and test auth-feign service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/auth/auth-feign

      - name: Build and test registry service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/registry

      - name: Build and test auth-service service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/auth/auth-service
      
      - name: Build and test gateway service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/gateway

      - name: Build and test stone-write service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/stone-write
        
      - name: Build and test stone-read service
        run: |
          mvn clean install -U
          mvn test
        working-directory: ./server/microservices/stone-read