name: Java CI & security check

on:
  push:
    branches:
      - DanielWorkflow
  pull_request:
    branches:
      - DanielWorkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install commons
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/libraries/commons

      - name: Build and test registry service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/registry

      - name: Build and test auth service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/auth

      - name: Build and test gateway service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/gateway

      - name: Download OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check.zip -d dependency-check
          ls -la dependency-check/bin

      - name: Run OWASP Dependency-Check
        run: |
          dependency-check/bin/dependency-check.sh --scan . --format ALL --out dependency-check-report

      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/