name: Java CI & security check

on:
  push:
    branches:
      - DanielWorkflow
  pull_request:
    branches:
      - DanielWorkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Install commons
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/libraries/commons

      - name: Build and test registry service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/registry

      - name: Build and test auth service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/auth

      - name: Build and test gateway service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/gateway

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
          --nvdApiKey ${{ secrets.NVD_API_KEY }}
          --scan . \
          --format ALL \
          --out ./dependency-check/dependency-check/bin/dependency-check-report \
          --failOnCVSS 7
        continue-on-error: true

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check/dependency-check/bin/dependency-check-report