name: Java CI & security check

on:
  push:
    branches:
      - DanielWorkflow
  pull_request:
    branches:
      - DanielWorkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install commons
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/libraries/commons

      - name: Build and test registry service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/registry

      - name: Build and test auth service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/auth

      - name: Build and test gateway service
        run: |
          mvn clean install
          mvn test
        working-directory: ./server/microservices/gateway

      - name: Create directory for report
        run: mkdir -p dependency-check-report

      - name: Run OWASP Dependency-Check using Docker
        run: |
          docker run --rm \
          -v $(pwd):/src \
          owasp/dependency-check \
          --scan /src \
          --format ALL \
          --out /src/dependency-check-report \
          --failOnCVSS 7 \
          --data /src/dependency-check-data

      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/