name: Java CI with Maven

on:
  push:
    branches: daniel/images_fix
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and analyze each microservice
      run: |
        # Define the path to each microservice
        for service in Kamyczki/server/microservices/*; do
          if [ -f "$service/pom.xml" ]; then
            echo "Running Maven build and analysis for $service"
            cd "$service"

            # Build with Maven
            mvn clean install --no-transfer-progress

            # Run SpotBugs
            mvn com.github.spotbugs:spotbugs-maven-plugin:4.7.0.0:check

            # Run Checkstyle
            mvn checkstyle:check

            # Run PMD
            mvn pmd:check

            # Run JaCoCo Test Coverage
            mvn test jacoco:report

            cd - # Return to root directory
          fi
        done

    - name: Upload JaCoCo Coverage Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-reports
        path: '**/target/site/jacoco'