name: Java code tests

on:
  push:
    branches: daniel/images_fix
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MICROSERVICES_PATH: ./server/microservices
      LIBRARIES_PATH: ./server/libraries

    strategy:
      matrix:
        service:
          - auth/auth-service
          - registry
          - gateway
          - stone-read
          - stone-write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build libraries
      run: mvn clean install --no-transfer-progress
      working-directory: ${{ env.LIBRARIES_PATH }}/commons
      continue-on-error: true

    - name: Build auth-feign-client
      run: mvn clean install --no-transfer-progress
      working-directory: ${{ env.MICROSERVICES_PATH }}/auth/auth-feign
      continue-on-error: true

    - name: Build with Maven
      working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.service }}
      run: mvn clean install --no-transfer-progress
      continue-on-error: true

    - name: Run SpotBugs
      working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.service }}
      run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.7.0.0:check
      continue-on-error: true

    - name: Run Checkstyle
      working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.service }}
      run: mvn checkstyle:check
      continue-on-error: true

    - name: Run PMD
      working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.service }}
      run: mvn pmd:check
      continue-on-error: true

    - name: Run JaCoCo Test Coverage
      working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.service }}
      run: mvn test jacoco:report
      continue-on-error: true

    - name: Upload JaCoCo Coverage Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report-${{ matrix.service }}
        path: ${{ env.MICROSERVICES_PATH }}/${{ matrix.service }}/target/site/jacoco
