name: Dependency Security Check

on:
  push:
    branches:
      - DanielWorkflow
  pull_request:
    branches:
      - DanielWorkflow

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check.zip -d dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan . --format ALL --out dependency-check-report

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report/