name: OWASP Dependency-Check Weekly

on:
  push:
    branches:
      - DanielWorkflow

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
          --scan . \
          --format ALL \
          --out ./dependency-check/dependency-check/bin/dependency-check-report \
          --failOnCVSS 7 \
          --nvdApiKey ${{ secrets.NVD_API_KEY }}
        continue-on-error: true

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check/dependency-check/bin/dependency-check-report
